const mongoose = require('mongoose')
const ItemSchema = new mongoose.Schema({
    peppypaneerpizza:{
        type:Number,
        min:0,
        max:20
    },
    cheeseandcornpizza:{
        type:Number,
        min:0,
        max:20
    },
    farmhousepizza:{
        type:Number,
        min:0,
        max:20
    },
    pineappleandcannedspaghettipizza:{
        type:Number,
        min:0,
        max:20
    },
    vegextravaganzapizza:{
        type:Number,
        min:0,
        max:20
    },
    mexicangreenwavepizza:{
        type:Number,
        min:0,
        max:20
    },
    punjabibaghpizza:{
        type:Number,
        min:0,
        max:20
    },
    margheritapizza:{
        type:Number,
        min:0,
        max:20
    },
    chickensausagepizza:{
        type:Number,
        min:0,
        max:20
    },
    indiantandoorichickentikkapizza:{
        type:Number,
        min:0,
        max:20
    },
    nonvegsupremepizza:{
        type:Number,
        min:0,
        max:20
    },
    chickendominatorpizza:{
        type:Number,
        min:0,
        max:20
    },
    chickenonionbarbequepizza:{
        type:Number,
        min:0,
        max:20
    },
    CheesePepperoniPizza:{
        type:Number,
        min:0,
        max:20
    },
    chickengoldendelightpizza:{
        type:Number,
        min:0,
        max:20
    },
    moroccanspicepastapizza:{
        type:Number,
        min:0,
        max:20
    },
    pepsi:{
        type:Number,
        min:0,
        max:20
    },
    sevenup:{
        type:Number,
        min:0,
        max:20
    },
    bailleyone:{
        type:Number,
        min:0,
        max:20
    },
    bnatural:{
        type:Number,
        min:0,
        max:20
    },
    redvelvetcake:{
        type:Number,
        min:0,
        max:20
    },
    chocolavacake:{
        type:Number,
        min:0,
        max:20
    },
    butterscotchmoussecake:{
        type:Number,
        min:0,
        max:20
    },
    browniefantasy:{
        type:Number,
        min:0,
        max:20
    }
})

const ItemModel = mongoose.model('Items', ItemSchema)
module.exports = ItemModel
